language_codes = {
    # European Languages
    'en': 'English',
    'fr': 'French',
    'es': 'Spanish',
    'de': 'German',
    'it': 'Italian',
    'pt': 'Portuguese',
    'nl': 'Dutch',
    'ru': 'Russian',
    'pl': 'Polish',
    'uk': 'Ukrainian',
    'el': 'Greek',
    'tr': 'Turkish',
    'sv': 'Swedish',
    'da': 'Danish',
    'no': 'Norwegian',
    'fi': 'Finnish',
    'is': 'Icelandic',
    'cs': 'Czech',
    'sk': 'Slovak',
    'hu': 'Hungarian',
    'ro': 'Romanian',
    'bg': 'Bulgarian',
    'sr': 'Serbian',
    'hr': 'Croatian',
    'bs': 'Bosnian',
    'sl': 'Slovenian',
    'et': 'Estonian',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'mk': 'Macedonian',
    'sq': 'Albanian',
    'mt': 'Maltese',
    
    # Asian Languages
    'zh': 'Chinese',
    'zh-cn': 'Chinese (Simplified)',
    'zh-tw': 'Chinese (Traditional)',
    'ja': 'Japanese',
    'ko': 'Korean',
    'hi': 'Hindi',
    'bn': 'Bengali',
    'te': 'Telugu',
    'ta': 'Tamil',
    'ur': 'Urdu',
    'pa': 'Punjabi',
    'gu': 'Gujarati',
    'kn': 'Kannada',
    'ml': 'Malayalam',
    'or': 'Odia',
    'ne': 'Nepali',
    'si': 'Sinhala',
    'my': 'Burmese',
    'km': 'Khmer',
    'lo': 'Lao',
    'th': 'Thai',
    'vi': 'Vietnamese',
    'ms': 'Malay',
    'id': 'Indonesian',
    'fil': 'Filipino',
    'tl': 'Tagalog',
    
    # Middle Eastern Languages
    'ar': 'Arabic',
    'he': 'Hebrew',
    'iw': 'Hebrew (old code)',
    'fa': 'Persian (Farsi)',
    'ps': 'Pashto',
    'ku': 'Kurdish',
    
    # South Asian Languages
    'am': 'Amharic',
    'ti': 'Tigrinya',
    'so': 'Somali',
    
    # African Languages
    'sw': 'Swahili',
    'zu': 'Zulu',
    'xh': 'Xhosa',
    'af': 'Afrikaans',
    'ha': 'Hausa',
    'yo': 'Yoruba',
    'ig': 'Igbo',
    
    # Other Major Languages
    'ca': 'Catalan',
    'gl': 'Galician',
    'eu': 'Basque',
    'cy': 'Welsh',
    'ga': 'Irish',
    'gd': 'Scottish Gaelic',
    'lb': 'Luxembourgish',
    'be': 'Belarusian',
    'hy': 'Armenian',
    'ka': 'Georgian',
    'mn': 'Mongolian',
    'az': 'Azerbaijani',
    'uz': 'Uzbek',
    'kk': 'Kazakh',
    'ky': 'Kyrgyz',
    'tg': 'Tajik',
    'tk': 'Turkmen',
}